name: Deploy Safety Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-safety-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('nextjs/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: nextjs
        run: pnpm install

      - name: Code quality check
        working-directory: nextjs
        run: pnpm lint

      - name: Type safety check
        working-directory: nextjs
        run: pnpm type-check

      - name: Test execution
        working-directory: nextjs
        run: pnpm test

      - name: Update deployment status
        if: github.event_name == 'pull_request'
        env:
          JOB_STATUS: ${{ job.status }}
        uses: actions/github-script@v7
        with:
          script: |
            const status = process.env.JOB_STATUS;
            const nodeVersion = process.env.NODE_VERSION;

            const message = status === 'success' 
              ? `<!-- DEPLOYMENT-CHECK -->
                 ✅ Code quality checks passed - Ready for review!
                 
                 📊 Check Results:
                 • Node.js: ${nodeVersion}
                 • Linting: ✅ Passed
                 • Type Safety: ✅ Passed
                 • Tests: ✅ Passed
                 • Status: All checks passed
                 
                 💡 Note: Production build will be verified by Vercel before deployment.
                 <!-- DEPLOYMENT-CHECK -->` 
              : `<!-- DEPLOYMENT-CHECK -->
                 ❌ Code quality checks failed - Fix issues before merging to main.
                 
                 🔍 Check the logs above for details.
                 <!-- DEPLOYMENT-CHECK -->`;

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.data.find(c => 
              c.user.type === 'Bot' && c.body.includes('<!-- DEPLOYMENT-CHECK -->')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: message
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
            }
