name: Deploy Safety Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-safety-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('nextjs/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: nextjs
        run: pnpm install

      - name: Code quality check
        working-directory: nextjs
        run: pnpm lint --max-warnings=0

      - name: Type safety check
        working-directory: nextjs
        run: pnpm type-check

      - name: Test execution
        working-directory: nextjs
        run: pnpm test:jest
